baseURL = "https://aoidayo.github.io/hugo-encrypt-showcase/"
languageCode = "zh-cn"
title = "Showcase"
theme = "hugo-theme-stack"

[pagination]
pagerSize = 5

[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = ""

[params.footer]
since = 2026
customText = ""

[params.sidebar]
compact = false
emoji = ""
subtitle = "A Hugo site powered by Stack."

[params.sidebar.avatar]
enabled = false
local = true
src = "img/avatar.png"

[params.article]
headingAnchor = false
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = false
provider = "disqus"

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
